# Generated by Django 5.2.7 on 2025-10-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkipper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopkeeper',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shopkeeperorder',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shopkeeperproduct',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
