# Generated by Django 5.2.7 on 2025-10-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_address_order_orderitem_paymentmethod_wallet_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
