# Generated by Django 5.2.7 on 2025-10-29 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_client_email_otp_client_otp_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevokedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(db_index=True, max_length=255, unique=True)),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('token_type', models.CharField(choices=[('access', 'Access'), ('refresh', 'Refresh')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revoked_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'revoked_tokens',
                'indexes': [models.Index(fields=['jti'], name='revoked_tok_jti_8c2714_idx'), models.Index(fields=['expires_at'], name='revoked_tok_expires_cdc4fe_idx')],
            },
        ),
    ]
