# Generated by Django 5.2.7 on 2025-10-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_latitude_product_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name']},
        ),
    ]
