# Generated by Django 5.2.7 on 2025-10-25 04:30

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_stock_product_is_available'),
        ('shopkeeper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopkeeper',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_picture'),
        ),
        migrations.AlterField(
            model_name='shopkeeperdocument',
            name='document_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shopkeeperdocument',
            name='document_type',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='shopkeeperdocument',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shopkeeperorder',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='shopkeeperorder',
            name='customer_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='shopkeeperorder',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopkeeperproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopkeeper_products', to='product.product'),
        ),
        migrations.AlterField(
            model_name='shopkeeperreview',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shopkeeperreview',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='shopkeeperreview',
            name='reviewer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
